import { PuzzleProps } from "./game"

export const puzzleList: PuzzleProps[] = [
  {
    id: 0,
    title: "Tutorial",
    description: "",
    sizeX: 8,
    sizeY: 1,
    stumps: [
      { x: 0, y: 0 },
      { x: 2, y: 0 },
      { x: 4, y: 0 },
      { x: 5, y: 0 },
      { x: 7, y: 0 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 7, y: 0 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 2, y: 0 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 5, y: 0 },
      },
    ],
  },
  {
    id: 100,
    title: "River Crossing 1",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 4, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 3, y: 1 },
      },
    ],
  },
  {
    id: 101,
    title: "River Crossing 2",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 4 },
      { x: 6, y: 4 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 4 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 1, y: 0 },
      },
      {
        start: { x: 2, y: 0 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 4, y: 2 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 102,
    title: "River Crossing 3",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 1 },
        end: { x: 3, y: 1 },
      },
    ],
  },
  {
    id: 103,
    title: "River Crossing 4",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 3, y: 4 },
      },
    ],
  },
  {
    id: 104,
    title: "River Crossing 5",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 1, y: 3 },
        end: { x: 1, y: 4 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 3 },
      },
    ],
  },
  {
    id: 105,
    title: "River Crossing 6",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 2, y: 1 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 106,
    title: "River Crossing 7",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 4, y: 2 },
      { x: 5, y: 0 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 2, y: 0 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 3, y: 3 },
      },
    ],
  },
  {
    id: 107,
    title: "River Crossing 8",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 2, y: 3 },
      },
      {
        start: { x: 2, y: 3 },
        end: { x: 5, y: 3 },
      },
      {
        start: { x: 3, y: 4 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 108,
    title: "River Crossing 9",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 500,
    title: "Warmup A",
    description: "from clickmazes.com",
    sizeX: 7,
    sizeY: 3,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 2, y: 2 },
      { x: 3, y: 1 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 4, y: 0 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 4, y: 2 },
      },
    ],
  },
  {
    id: 109,
    title: "River Crossing 10",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 3, y: 2 },
        end: { x: 3, y: 4 },
      },
    ],
  },
  {
    id: 110,
    title: "River Crossing 11",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 1, y: 2 },
      },
    ],
  },
  {
    id: 111,
    title: "River Crossing 12",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 4 },
      { x: 4, y: 3 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 1, y: 0 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 2, y: 4 },
      },
    ],
  },
  {
    id: 112,
    title: "River Crossing 13",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 3, y: 4 },
      },
    ],
  },
  {
    id: 113,
    title: "River Crossing 14",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 3 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 1, y: 3 },
        end: { x: 4, y: 3 },
      },
      {
        start: { x: 5, y: 0 },
        end: { x: 5, y: 2 },
      },
    ],
  },
  {
    id: 501,
    title: "Warmup B",
    description: "from clickmazes.com",
    sizeX: 10,
    sizeY: 3,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 2, y: 1 },
      { x: 3, y: 2 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 5, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 2 },
      { x: 8, y: 0 },
      { x: 8, y: 2 },
      { x: 9, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 9, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 5, y: 0 },
        end: { x: 8, y: 0 },
      },
      {
        start: { x: 6, y: 1 },
        end: { x: 6, y: 2 },
      },
    ],
  },
  {
    id: 114,
    title: "River Crossing 15",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 2 },
      },
      {
        start: { x: 4, y: 3 },
        end: { x: 4, y: 4 },
      },
      {
        start: { x: 5, y: 1 },
        end: { x: 5, y: 4 },
      },
    ],
  },
  {
    id: 115,
    title: "River Crossing 16",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 116,
    title: "River Crossing 17",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 3 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 1, y: 3 },
        end: { x: 3, y: 3 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 3, y: 1 },
      },
    ],
  },
  {
    id: 117,
    title: "River Crossing 18",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 3, y: 3 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 3 },
      },
      {
        start: { x: 4, y: 3 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 502,
    title: "Warmup C",
    description: "from clickmazes.com",
    sizeX: 10,
    sizeY: 3,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 6, y: 1 },
      { x: 6, y: 2 },
      { x: 8, y: 0 },
      { x: 8, y: 2 },
      { x: 9, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 9, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 1 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 5, y: 2 },
      },
    ],
  },
  {
    id: 118,
    title: "River Crossing 19",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 4, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 5, y: 1 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
    ],
  },
  {
    id: 119,
    title: "River Crossing 20",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 3, y: 1 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 4, y: 2 },
        end: { x: 4, y: 4 },
      },
      {
        start: { x: 5, y: 2 },
        end: { x: 5, y: 4 },
      },
    ],
  },
  {
    id: 120,
    title: "River Crossing 21",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 5, y: 1 },
      },
    ],
  },
  {
    id: 121,
    title: "River Crossing 22",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 0 },
      { x: 0, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 2 },
      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 6, y: 4 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 4 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 5, y: 0 },
      },
      {
        start: { x: 4, y: 2 },
        end: { x: 5, y: 2 },
      },
      {
        start: { x: 3, y: 3 },
        end: { x: 3, y: 4 },
      },
    ],
  },
  {
    id: 122,
    title: "River Crossing 23",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 4 },
      { x: 3, y: 2 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 4, y: 1 },
        end: { x: 4, y: 3 },
      },
    ],
  },
  {
    id: 503,
    title: "Warmup D",
    description: "from clickmazes.com",
    sizeX: 10,
    sizeY: 3,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 0 },
      { x: 7, y: 0 },
      { x: 7, y: 1 },
      { x: 8, y: 2 },
      { x: 9, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 9, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 0 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 4, y: 2 },
      },
    ],
  },

  {
    id: 123,
    title: "River Crossing 24",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 3 },
      { x: 2, y: 4 },
      { x: 3, y: 1 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 2, y: 0 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 5, y: 0 },
        end: { x: 5, y: 3 },
      },
    ],
  },
  {
    id: 124,
    title: "River Crossing 25",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 4, y: 4 },
      },
      {
        start: { x: 4, y: 4 },
        end: { x: 5, y: 4 },
      },
    ],
  },
  {
    id: 504,
    title: "Warmup E",
    description: "from clickmazes.com",
    sizeX: 10,
    sizeY: 3,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 2, y: 2 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 4, y: 1 },
      { x: 4, y: 2 },
      { x: 6, y: 0 },
      { x: 6, y: 2 },
      { x: 7, y: 1 },
      { x: 7, y: 2 },
      { x: 8, y: 0 },
      { x: 9, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 9, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 3, y: 1 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 3, y: 1 },
      },
    ],
  },
  {
    id: 125,
    title: "River Crossing 26",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 1, y: 4 },
      },
      {
        start: { x: 4, y: 1 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 126,
    title: "River Crossing 27",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 2, y: 3 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 2, y: 3 },
        end: { x: 3, y: 3 },
      },
    ],
  },
  {
    id: 127,
    title: "River Crossing 28",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 4 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 1 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 4 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 4 },
        end: { x: 1, y: 4 },
      },
      {
        start: { x: 1, y: 1 },
        end: { x: 3, y: 1 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 3 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 128,
    title: "River Crossing 29",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 3 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 5, y: 1 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 3, y: 2 },
        end: { x: 3, y: 4 },
      },
    ],
  },
  {
    id: 129,
    title: "River Crossing 30",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 5, y: 1 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 1, y: 4 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 5, y: 0 },
      },
    ],
  },
  {
    id: 130,
    title: "River Crossing 31",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 5, y: 1 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 5, y: 0 },
      },
      {
        start: { x: 2, y: 3 },
        end: { x: 5, y: 3 },
      },
    ],
  },
  {
    id: 131,
    title: "River Crossing 32",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 3, y: 4 },
      },
      {
        start: { x: 4, y: 1 },
        end: { x: 4, y: 3 },
      },
    ],
  },
  {
    id: 132,
    title: "River Crossing 33",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 2, y: 3 },
      },
      {
        start: { x: 5, y: 0 },
        end: { x: 5, y: 2 },
      },
    ],
  },
  {
    id: 133,
    title: "River Crossing 34",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 1, y: 0 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 3, y: 2 },
      },
    ],
  },
  {
    id: 134,
    title: "River Crossing 35",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 5, y: 2 },
        end: { x: 5, y: 4 },
      },
    ],
  },
  {
    id: 135,
    title: "River Crossing 36",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 4 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 3, y: 3 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 3, y: 3 },
        end: { x: 3, y: 2 },
      },
    ],
  },
  {
    id: 136,
    title: "River Crossing 37",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 1 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 4, y: 4 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 2 },
      },
    ],
  },
  {
    id: 137,
    title: "River Crossing 38",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 2, y: 3 },
        end: { x: 5, y: 3 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 5, y: 0 },
      },
    ],
  },
  {
    id: 138,
    title: "River Crossing 39",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 2 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 3, y: 2 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 3, y: 2 },
        end: { x: 3, y: 4 },
      },
      {
        start: { x: 1, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 1, y: 3 },
        end: { x: 2, y: 3 },
      },
    ],
  },
  {
    id: 139,
    title: "River Crossing 40",
    description: "from River Crossing",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 3, y: 4 },
      },
      {
        start: { x: 2, y: 3 },
        end: { x: 5, y: 3 },
      },
    ],
  },
  {
    id: 200,
    title: "River Crossing Bonus 1",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 3,
    stumps: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 4, y: 1 },
      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 1, y: 0 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 2, y: 0 },
      },
      {
        start: { x: 2, y: 0 },
        end: { x: 5, y: 0 },
      },
    ],
  },
  {
    id: 201,
    title: "River Crossing Bonus 2",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 4 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 6, y: 4 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 1, y: 0 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 2, y: 2 },
      },
    ],
  },
  {
    id: 202,
    title: "River Crossing Bonus 3",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 3, y: 1 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 3, y: 1 },
      },
    ],
  },
  {
    id: 203,
    title: "River Crossing Bonus 4",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 4, y: 2 },
      },
      {
        start: { x: 4, y: 4 },
        end: { x: 5, y: 4 },
      },
    ],
  },
  {
    id: 204,
    title: "River Crossing Bonus 5",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 1, y: 1 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 205,
    title: "River Crossing Bonus 6",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 4, y: 1 },
      { x: 4, y: 2 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 3, y: 3 },
      },
    ],
  },
  {
    id: 206,
    title: "River Crossing Bonus 7",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 3 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 4, y: 1 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 207,
    title: "River Crossing Bonus 8",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 4 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 1, y: 4 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 2, y: 1 },
        end: { x: 5, y: 1 },
      },
    ],
  },
  {
    id: 208,
    title: "River Crossing Bonus 9",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 3 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 6, y: 1 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 1 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 2, y: 0 },
        end: { x: 2, y: 3 },
      },
      {
        start: { x: 3, y: 2 },
        end: { x: 3, y: 4 },
      },
      {
        start: { x: 5, y: 0 },
        end: { x: 5, y: 2 },
      },
    ],
  },
  {
    id: 209,
    title: "River Crossing Bonus 10",
    description: "from River Crossing's Bonus Challenges",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 3 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 2, y: 1 },
      { x: 2, y: 3 },
      { x: 3, y: 0 },
      { x: 3, y: 2 },
      { x: 3, y: 4 },
      { x: 4, y: 0 },
      { x: 5, y: 0 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 3 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 3 },
        end: { x: 2, y: 3 },
      },
      {
        start: { x: 1, y: 1 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 2, y: 3 },
        end: { x: 5, y: 3 },
      },
      {
        start: { x: 4, y: 0 },
        end: { x: 5, y: 0 },
      },
    ],
  },
  {
    id: 300,
    title: "Deep End",
    description: "from clickmazes.com",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 1 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 3 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 6, y: 3 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 2, y: 1 },
      },
      {
        start: { x: 1, y: 4 },
        end: { x: 2, y: 4 },
      },
      {
        start: { x: 4, y: 1 },
        end: { x: 4, y: 4 },
      },
    ],
  },
  {
    id: 301,
    title: "Smash Hit",
    description: "from clickmazes.com",
    sizeX: 10,
    sizeY: 8,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 6 },
      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 2, y: 7 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 5 },
      { x: 3, y: 7 },
      { x: 4, y: 0 },
      { x: 4, y: 4 },
      { x: 4, y: 5 },
      { x: 5, y: 2 },
      { x: 5, y: 5 },
      { x: 5, y: 6 },
      { x: 5, y: 7 },
      { x: 6, y: 2 },
      { x: 6, y: 3 },
      { x: 6, y: 4 },
      { x: 6, y: 7 },
      { x: 7, y: 0 },
      { x: 7, y: 2 },
      { x: 7, y: 5 },
      { x: 8, y: 0 },
      { x: 8, y: 1 },
      { x: 8, y: 3 },
      { x: 8, y: 6 },
      { x: 9, y: 5 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 9, y: 5 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 2, y: 4 },
        end: { x: 2, y: 7 },
      },
      {
        start: { x: 6, y: 3 },
        end: { x: 6, y: 4 },
      },
    ],
  },
  {
    id: 302,
    title: "Route-66",
    description: "from clickmazes.com",
    sizeX: 11,
    sizeY: 9,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 7 },
      { x: 1, y: 8 },
      { x: 2, y: 3 },
      { x: 2, y: 6 },
      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },
      { x: 3, y: 7 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 4, y: 6 },
      { x: 4, y: 8 },
      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 7 },
      { x: 6, y: 1 },
      { x: 6, y: 5 },
      { x: 6, y: 8 },
      { x: 7, y: 1 },
      { x: 7, y: 2 },
      { x: 7, y: 4 },
      { x: 7, y: 5 },
      { x: 8, y: 0 },
      { x: 8, y: 3 },
      { x: 8, y: 6 },
      { x: 8, y: 7 },
      { x: 9, y: 1 },
      { x: 9, y: 3 },
      { x: 9, y: 5 },
      { x: 9, y: 7 },
      { x: 9, y: 8 },
      { x: 10, y: 6 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 10, y: 6 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 3, y: 2 },
      },
      {
        start: { x: 4, y: 8 },
        end: { x: 6, y: 8 },
      },
      {
        start: { x: 6, y: 5 },
        end: { x: 7, y: 5 },
      },
    ],
  },
  {
    id: 303,
    title: "Staircase",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 7,
    sizeY: 5,
    stumps: [
      { x: 0, y: 2 },
      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 2, y: 0 },
      { x: 2, y: 2 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 0 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 1 },
      { x: 5, y: 4 },
      { x: 6, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 6, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 2, y: 0 },
      },
      {
        start: { x: 5, y: 1 },
        end: { x: 5, y: 4 },
      },
    ],
  },
  {
    id: 304,
    title: "Six-squared",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 8,
    sizeY: 6,
    stumps: [
      { x: 0, y: 2 },

      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },

      { x: 2, y: 2 },
      { x: 2, y: 4 },

      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },

      { x: 4, y: 1 },
      { x: 4, y: 2 },
      { x: 4, y: 3 },
      { x: 4, y: 5 },

      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },

      { x: 6, y: 0 },
      { x: 6, y: 2 },
      { x: 6, y: 5 },

      { x: 7, y: 5 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 7, y: 5 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 6, y: 0 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 4, y: 1 },
      },
    ],
  },
  {
    id: 305,
    title: "Six-squared",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 8,
    sizeY: 6,
    stumps: [
      { x: 0, y: 2 },

      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },

      { x: 2, y: 2 },
      { x: 2, y: 4 },

      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },

      { x: 4, y: 1 },
      { x: 4, y: 2 },
      { x: 4, y: 3 },
      { x: 4, y: 5 },

      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },

      { x: 6, y: 0 },
      { x: 6, y: 2 },
      { x: 6, y: 5 },

      { x: 7, y: 5 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 7, y: 5 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 6, y: 0 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 4, y: 1 },
      },
    ],
  },
  {
    id: 306,
    title: "Expressway",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 9,
    sizeY: 7,
    stumps: [
      { x: 0, y: 2 },

      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },
      { x: 1, y: 6 },

      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 2, y: 6 },

      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },

      { x: 4, y: 4 },
      { x: 4, y: 6 },

      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 5 },
      { x: 5, y: 6 },

      { x: 6, y: 0 },
      { x: 6, y: 3 },
      { x: 6, y: 5 },

      { x: 7, y: 0 },
      { x: 7, y: 3 },
      { x: 7, y: 4 },
      { x: 7, y: 6 },

      { x: 8, y: 2 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 8, y: 2 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 3, y: 4 },
        end: { x: 4, y: 4 },
      },
      {
        start: { x: 4, y: 4 },
        end: { x: 7, y: 4 },
      },
    ],
  },
  {
    id: 307,
    title: "Box Step",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 9,
    sizeY: 7,
    stumps: [
      { x: 0, y: 1 },

      { x: 1, y: 0 },
      { x: 1, y: 3 },
      { x: 1, y: 6 },

      { x: 2, y: 2 },
      { x: 2, y: 5 },
      { x: 2, y: 6 },

      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 2 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },

      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },

      { x: 5, y: 1 },
      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 4 },
      { x: 5, y: 6 },

      { x: 6, y: 2 },

      { x: 7, y: 0 },
      { x: 7, y: 1 },
      { x: 7, y: 3 },

      { x: 8, y: 4 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 8, y: 4 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 3, y: 1 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 5, y: 1 },
      },
      {
        start: { x: 3, y: 3 },
        end: { x: 3, y: 4 },
      },
    ],
  },
  {
    id: 308,
    title: "Brute 66",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 9,
    sizeY: 8,
    stumps: [
      { x: 0, y: 2 },

      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 6 },

      { x: 2, y: 0 },
      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 2, y: 7 },

      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },

      { x: 4, y: 1 },
      { x: 4, y: 3 },
      { x: 4, y: 4 },
      { x: 4, y: 7 },

      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 5 },

      { x: 6, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 4 },
      { x: 6, y: 5 },
      { x: 6, y: 6 },

      { x: 7, y: 0 },
      { x: 7, y: 1 },
      { x: 7, y: 3 },
      { x: 7, y: 5 },
      { x: 7, y: 7 },

      { x: 8, y: 6 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 8, y: 6 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 2, y: 2 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 1, y: 1 },
      },
      {
        start: { x: 6, y: 1 },
        end: { x: 6, y: 4 },
      },
    ],
  },
  {
    id: 309,
    title: "Trebuchet V2",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 11,
    sizeY: 9,
    stumps: [
      { x: 0, y: 2 },

      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 6 },

      { x: 2, y: 0 },
      { x: 2, y: 3 },
      { x: 2, y: 5 },

      { x: 3, y: 0 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 8 },

      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 4, y: 6 },
      { x: 4, y: 8 },

      { x: 5, y: 4 },
      { x: 5, y: 5 },
      { x: 5, y: 8 },

      { x: 6, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 2 },
      { x: 6, y: 3 },
      { x: 6, y: 4 },
      { x: 6, y: 5 },
      { x: 6, y: 6 },
      { x: 6, y: 7 },
      { x: 6, y: 8 },

      { x: 7, y: 0 },
      { x: 7, y: 3 },
      { x: 7, y: 7 },
      { x: 7, y: 8 },

      { x: 8, y: 1 },
      { x: 8, y: 3 },
      { x: 8, y: 5 },

      { x: 9, y: 0 },
      { x: 9, y: 1 },
      { x: 9, y: 6 },
      { x: 9, y: 7 },
      { x: 9, y: 8 },

      { x: 10, y: 8 },
    ],
    start: { x: 0, y: 2 },
    destination: { x: 10, y: 8 },
    planks: [
      {
        start: { x: 0, y: 2 },
        end: { x: 1, y: 2 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 4, y: 2 },
      },
      {
        start: { x: 7, y: 0 },
        end: { x: 9, y: 0 },
      },
    ],
  },
  {
    id: 310,
    title: "Shuttle",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 11,
    sizeY: 9,
    stumps: [
      { x: 0, y: 1 },

      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 5 },
      { x: 1, y: 8 },

      { x: 2, y: 5 },

      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },
      { x: 3, y: 7 },
      { x: 3, y: 8 },

      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 4, y: 5 },

      { x: 5, y: 4 },
      { x: 5, y: 6 },
      { x: 5, y: 8 },

      { x: 6, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 5 },
      { x: 6, y: 6 },
      { x: 6, y: 7 },
      { x: 6, y: 8 },

      { x: 7, y: 5 },
      { x: 7, y: 8 },

      { x: 8, y: 1 },
      { x: 8, y: 3 },
      { x: 8, y: 8 },

      { x: 9, y: 0 },
      { x: 9, y: 1 },
      { x: 9, y: 2 },
      { x: 9, y: 3 },
      { x: 9, y: 5 },
      { x: 9, y: 6 },

      { x: 10, y: 8 },
    ],
    start: { x: 0, y: 1 },
    destination: { x: 10, y: 8 },
    planks: [
      {
        start: { x: 0, y: 1 },
        end: { x: 3, y: 1 },
      },
      {
        start: { x: 3, y: 4 },
        end: { x: 4, y: 4 },
      },
      {
        start: { x: 9, y: 3 },
        end: { x: 9, y: 5 },
      },
    ],
  },
  {
    id: 311,
    title: "Pennsylvania",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 12,
    sizeY: 10,
    stumps: [
      { x: 0, y: 0 },

      { x: 1, y: 8 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },

      { x: 2, y: 5 },
      { x: 2, y: 6 },
      { x: 2, y: 8 },
      { x: 2, y: 9 },

      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 3, y: 9 },

      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 4, y: 5 },
      { x: 4, y: 8 },
      { x: 4, y: 9 },

      { x: 5, y: 0 },
      { x: 5, y: 1 },
      { x: 5, y: 5 },
      { x: 5, y: 9 },

      { x: 6, y: 2 },
      { x: 6, y: 3 },
      { x: 6, y: 6 },

      { x: 7, y: 0 },
      { x: 7, y: 1 },
      { x: 7, y: 2 },
      { x: 7, y: 4 },
      { x: 7, y: 7 },

      { x: 8, y: 2 },
      { x: 8, y: 4 },
      { x: 8, y: 5 },
      { x: 8, y: 8 },
      { x: 8, y: 9 },

      { x: 9, y: 0 },
      { x: 9, y: 3 },
      { x: 9, y: 5 },
      { x: 9, y: 6 },
      { x: 9, y: 9 },

      { x: 10, y: 0 },
      { x: 10, y: 3 },
      { x: 10, y: 6 },

      { x: 11, y: 9 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 11, y: 9 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 2, y: 6 },
        end: { x: 2, y: 8 },
      },
      {
        start: { x: 9, y: 0 },
        end: { x: 10, y: 0 },
      },
    ],
  },
  {
    id: 312,
    title: "Parallel Universe",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 12,
    sizeY: 10,
    stumps: [
      { x: 0, y: 8 },

      { x: 1, y: 0 },
      { x: 1, y: 4 },
      { x: 1, y: 7 },

      { x: 2, y: 4 },
      { x: 2, y: 6 },

      { x: 3, y: 0 },
      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 9 },

      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 4, y: 8 },

      { x: 5, y: 3 },
      { x: 5, y: 7 },
      { x: 5, y: 9 },

      { x: 6, y: 1 },
      { x: 6, y: 2 },
      { x: 6, y: 6 },
      { x: 6, y: 7 },
      { x: 6, y: 9 },

      { x: 7, y: 1 },
      { x: 7, y: 5 },
      { x: 7, y: 8 },
      { x: 7, y: 9 },

      { x: 8, y: 0 },
      { x: 8, y: 4 },
      { x: 8, y: 7 },

      { x: 9, y: 3 },
      { x: 9, y: 5 },
      { x: 9, y: 7 },
      { x: 9, y: 8 },

      { x: 10, y: 2 },
      { x: 10, y: 5 },
      { x: 10, y: 9 },

      { x: 11, y: 1 },
    ],
    start: { x: 0, y: 8 },
    destination: { x: 11, y: 1 },
    planks: [
      {
        start: { x: 0, y: 8 },
        end: { x: 4, y: 8 },
      },
      {
        start: { x: 3, y: 0 },
        end: { x: 4, y: 0 },
      },
      {
        start: { x: 3, y: 1 },
        end: { x: 3, y: 4 },
      },
      {
        start: { x: 3, y: 9 },
        end: { x: 5, y: 9 },
      },
    ],
  },
  {
    id: 313,
    title: "Special Delivery",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 12,
    sizeY: 10,
    stumps: [
      { x: 0, y: 8 },

      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 5 },

      { x: 2, y: 1 },
      { x: 2, y: 6 },
      { x: 2, y: 6 },

      { x: 3, y: 0 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 9 },

      { x: 4, y: 1 },
      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 4, y: 8 },

      { x: 5, y: 3 },
      { x: 5, y: 7 },

      { x: 6, y: 2 },
      { x: 6, y: 6 },
      { x: 6, y: 7 },
      { x: 6, y: 9 },

      { x: 7, y: 0 },
      { x: 7, y: 6 },

      { x: 8, y: 2 },
      { x: 8, y: 4 },
      { x: 8, y: 6 },
      { x: 8, y: 8 },

      { x: 9, y: 0 },
      { x: 9, y: 1 },
      { x: 9, y: 2 },
      { x: 9, y: 3 },
      { x: 9, y: 6 },
      { x: 9, y: 7 },
      { x: 9, y: 9 },

      { x: 10, y: 8 },

      { x: 11, y: 1 },
    ],
    start: { x: 0, y: 8 },
    destination: { x: 11, y: 1 },
    planks: [
      {
        start: { x: 0, y: 8 },
        end: { x: 4, y: 8 },
      },
      {
        start: { x: 1, y: 2 },
        end: { x: 4, y: 2 },
      },
      {
        start: { x: 4, y: 1 },
        end: { x: 4, y: 2 },
      },
      {
        start: { x: 8, y: 8 },
        end: { x: 10, y: 8 },
      },
    ],
  },
  {
    id: 314,
    title: "Junior",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 10,
    sizeY: 8,
    stumps: [
      { x: 0, y: 0 },

      { x: 1, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 6 },

      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 3, y: 5 },
      { x: 3, y: 7 },

      { x: 4, y: 0 },
      { x: 4, y: 2 },
      { x: 4, y: 5 },

      { x: 5, y: 1 },
      { x: 5, y: 3 },
      { x: 5, y: 7 },

      { x: 6, y: 0 },
      { x: 6, y: 1 },
      { x: 6, y: 4 },
      { x: 6, y: 5 },
      { x: 6, y: 7 },

      { x: 7, y: 0 },
      { x: 7, y: 2 },
      { x: 7, y: 7 },

      { x: 8, y: 0 },
      { x: 8, y: 3 },
      { x: 8, y: 7 },

      { x: 9, y: 5 },
    ],
    start: { x: 0, y: 0 },
    destination: { x: 9, y: 5 },
    planks: [
      {
        start: { x: 0, y: 0 },
        end: { x: 1, y: 0 },
      },
      {
        start: { x: 1, y: 1 },
        end: { x: 1, y: 3 },
      },
      {
        start: { x: 1, y: 3 },
        end: { x: 1, y: 6 },
      },
      {
        start: { x: 5, y: 3 },
        end: { x: 5, y: 7 },
      },
      {
        start: { x: 7, y: 2 },
        end: { x: 7, y: 7 },
      },
    ],
  },
  {
    id: 315,
    title: "Stack of Five",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 11,
    sizeY: 9,
    stumps: [
      { x: 0, y: 4 },

      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 5 },
      { x: 1, y: 8 },

      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 6 },

      { x: 3, y: 0 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 3, y: 7 },
      { x: 3, y: 8 },

      { x: 5, y: 1 },
      { x: 5, y: 2 },

      { x: 6, y: 1 },
      { x: 6, y: 4 },
      { x: 6, y: 5 },
      { x: 6, y: 6 },

      { x: 7, y: 2 },
      { x: 7, y: 4 },
      { x: 7, y: 6 },
      { x: 7, y: 8 },

      { x: 8, y: 0 },
      { x: 8, y: 2 },
      { x: 8, y: 3 },
      { x: 8, y: 4 },
      { x: 8, y: 5 },
      { x: 8, y: 6 },
      { x: 8, y: 7 },
      { x: 8, y: 8 },

      { x: 9, y: 3 },
      { x: 9, y: 4 },
      { x: 9, y: 8 },

      { x: 10, y: 6 },
    ],
    start: { x: 0, y: 4 },
    destination: { x: 10, y: 6 },
    planks: [
      {
        start: { x: 0, y: 4 },
        end: { x: 3, y: 4 },
      },
      {
        start: { x: 1, y: 0 },
        end: { x: 3, y: 0 },
      },
      {
        start: { x: 5, y: 1 },
        end: { x: 6, y: 1 },
      },
      {
        start: { x: 2, y: 6 },
        end: { x: 6, y: 6 },
      },
      {
        start: { x: 3, y: 7 },
        end: { x: 8, y: 7 },
      },
    ],
  },
  {
    id: 316,
    title: "Conundrum",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 12,
    sizeY: 10,
    stumps: [
      { x: 0, y: 6 },

      { x: 1, y: 1 },
      { x: 1, y: 3 },
      { x: 1, y: 5 },
      { x: 1, y: 6 },
      { x: 1, y: 9 },

      { x: 2, y: 4 },
      { x: 2, y: 6 },
      { x: 2, y: 9 },

      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },
      { x: 3, y: 9 },

      { x: 4, y: 2 },
      { x: 4, y: 4 },
      { x: 4, y: 8 },

      { x: 5, y: 0 },
      { x: 5, y: 2 },
      { x: 5, y: 3 },
      { x: 5, y: 7 },
      { x: 5, y: 8 },
      { x: 5, y: 9 },

      { x: 6, y: 6 },

      { x: 7, y: 3 },

      { x: 8, y: 0 },
      { x: 8, y: 5 },
      { x: 8, y: 8 },

      { x: 9, y: 0 },
      { x: 9, y: 1 },
      { x: 9, y: 2 },

      { x: 10, y: 1 },
      { x: 10, y: 6 },
      { x: 10, y: 7 },
      { x: 10, y: 9 },

      { x: 11, y: 0 },
    ],
    start: { x: 0, y: 6 },
    destination: { x: 11, y: 0 },
    planks: [
      {
        start: { x: 0, y: 6 },
        end: { x: 1, y: 6 },
      },
      {
        start: { x: 1, y: 3 },
        end: { x: 1, y: 5 },
      },
      {
        start: { x: 1, y: 6 },
        end: { x: 1, y: 9 },
      },
      {
        start: { x: 4, y: 4 },
        end: { x: 4, y: 8 },
      },
      {
        start: { x: 10, y: 1 },
        end: { x: 10, y: 6 },
      },
    ],
  },
  {
    id: 317,
    title: "Fort Mudge",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 12,
    sizeY: 10,
    stumps: [
      { x: 0, y: 6 },

      { x: 1, y: 0 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 5 },
      { x: 1, y: 8 },

      { x: 2, y: 2 },
      { x: 2, y: 6 },
      { x: 2, y: 8 },
      { x: 2, y: 9 },

      { x: 3, y: 1 },
      { x: 3, y: 4 },
      { x: 3, y: 5 },
      { x: 3, y: 6 },
      { x: 3, y: 8 },
      { x: 3, y: 9 },

      { x: 5, y: 0 },
      { x: 5, y: 4 },
      { x: 5, y: 7 },
      { x: 5, y: 8 },
      { x: 5, y: 9 },

      { x: 6, y: 2 },
      { x: 6, y: 6 },

      { x: 7, y: 1 },
      { x: 7, y: 9 },

      { x: 8, y: 2 },
      { x: 8, y: 3 },
      { x: 8, y: 5 },
      { x: 8, y: 8 },

      { x: 9, y: 1 },
      { x: 9, y: 2 },
      { x: 9, y: 3 },
      { x: 9, y: 6 },
      { x: 9, y: 7 },

      { x: 10, y: 0 },
      { x: 10, y: 3 },
      { x: 10, y: 4 },
      { x: 10, y: 9 },

      { x: 11, y: 1 },
    ],
    start: { x: 0, y: 6 },
    destination: { x: 11, y: 1 },
    planks: [
      {
        start: { x: 0, y: 6 },
        end: { x: 2, y: 6 },
      },
      {
        start: { x: 2, y: 2 },
        end: { x: 6, y: 2 },
      },
      {
        start: { x: 2, y: 8 },
        end: { x: 2, y: 9 },
      },
      {
        start: { x: 6, y: 6 },
        end: { x: 9, y: 6 },
      },
      {
        start: { x: 10, y: 4 },
        end: { x: 10, y: 9 },
      },
    ],
  },
  {
    id: 318,
    title: "Revenge",
    description: "from clickmazes.com - Swampbeast",
    sizeX: 12,
    sizeY: 10,
    stumps: [
      { x: 0, y: 4 },

      { x: 1, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 4 },
      { x: 1, y: 6 },
      { x: 1, y: 8 },

      { x: 2, y: 1 },
      { x: 2, y: 2 },
      { x: 2, y: 4 },
      { x: 2, y: 5 },
      { x: 2, y: 7 },

      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 3, y: 4 },
      { x: 3, y: 7 },

      { x: 4, y: 0 },
      { x: 4, y: 1 },
      { x: 4, y: 4 },
      { x: 4, y: 8 },

      { x: 5, y: 1 },
      { x: 5, y: 3 },

      { x: 6, y: 0 },
      { x: 6, y: 3 },
      { x: 6, y: 5 },
      { x: 6, y: 7 },
      { x: 6, y: 9 },

      { x: 7, y: 2 },
      { x: 7, y: 4 },
      { x: 7, y: 9 },

      { x: 8, y: 1 },
      { x: 8, y: 5 },
      { x: 8, y: 8 },

      { x: 9, y: 2 },
      { x: 9, y: 7 },
      { x: 9, y: 8 },

      { x: 10, y: 0 },

      { x: 11, y: 4 },
    ],
    start: { x: 0, y: 4 },
    destination: { x: 11, y: 4 },
    planks: [
      {
        start: { x: 0, y: 4 },
        end: { x: 1, y: 4 },
      },
      {
        start: { x: 2, y: 5 },
        end: { x: 2, y: 7 },
      },
      {
        start: { x: 6, y: 0 },
        end: { x: 6, y: 3 },
      },
      {
        start: { x: 7, y: 4 },
        end: { x: 7, y: 9 },
      },
      {
        start: { x: 8, y: 1 },
        end: { x: 8, y: 5 },
      },
    ],
  },
]
